repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      - id: ruff-check
        args: ["--fix"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      - id: ruff-format
  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: v0.0.55
    hooks:
      - id: ty
        additional_dependencies:
          - mne==1.12.1
          - pyvista==0.48.4
          - numpy==2.5.0
          - qtpy==2.4.3
          - pytest-qt==4.5.0
          - pytest-mock==3.15.1
          - traitlets==5.15.1
          - pyside6==6.11.1
        args: [--no-python-downloads, --no-project]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: [--strict, -c, .yamllint.yml]
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.4
    hooks:
      - id: toml-sort-fix
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        types_or: [python, bib, rst, inc]
