name: 'Tests'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    name: '${{ matrix.os }} / ${{ matrix.kind }} / ${{ matrix.python }}'
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    defaults:
      run:
        shell: bash -el {0}
    env:
      PYTHON_VERSION: '${{ matrix.python }}'
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: '3.13'
            kind: 'dev'
          - os: ubuntu-latest
            python: '3.10'
            kind: 'stable'
          - os: macos-latest
            python: '3.11'
            kind: 'stable'
          - os: windows-latest
            python: '3.12'
            kind: 'stable'
    steps:
      - uses: actions/checkout@v7
      - uses: pyvista/setup-headless-display-action@main
      - uses: mamba-org/setup-micromamba@v3
        timeout-minutes: 8
        with:
          environment-file: environment.yml
          # Pin some packages to facilitate speed of solving
          create-args: >-
            python=${{ matrix.python }} mayavi=4.8.3 traitsui=8.0.0 pyface=8.0.0 pyside6=6.9.1 qt6-main=6.9.1 vtk-base=9.4.2 vtk=9.4.2 noqt5=1.0.0
      - run: python -m pip install --progress-bar off -e .[test] qtpy nibabel defusedxml --only-binary=":all:"
      - run: python -m pip install --upgrade "mne @ https://github.com/mne-tools/mne-python/archive/refs/heads/main.zip"
        if: matrix.kind == 'dev'
      - run: mne sys_info -p
      - run: python -c "from mayavi import mlab; mlab.test_plot3d()"
      - run: python -c "import mne; mne.datasets.testing.data_path(verbose=True)"
      - run: pytest --tb=short --cov=mne_kit_gui --cov-report=xml --cov-report=html -vvv mne_kit_gui
      - uses: codecov/codecov-action@v7
        with:
          token: 325dd076-62e1-4ca3-9e9a-c510d101e173
        if: success() || failure()
